### ISSUE TITLE
Apparently randomize main rules is broken

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1012]
But nobody could tell me exactly how.

**Comment by LostThePirate** [comment]
I'm not sure what else occurs, but Closed Forest + Start As: Adult will generate successfully, even though they are otherwise incompatible.
Iirc, there are also problems with Triforce Hunt and the Ganon's BK getting placed (even though it's supposed to be disabled and given upon completion of the hunt).

**Comment by Zannick** [comment]
Hm, so the mechanism that disables other settings doesn't occur when randomizing them. That is, we only disable settings based on **chosen** settings. When randomizing, we just use the distributions straight-up.

So it looks like each individual contradiction has to be prevented at the appropriate place, unless we rework the disable mechanism or add some sort of 'imply' mechanism to take care of it.

**Comment by r0bd0g** [comment]
I'm not saying to actually get rid of randomize main rules, I just want to ask the question of if we need it. Generally when people want randomized settings they use a script to do it anyway...

**Comment by Hamsda** [comment]
There is probably still a lot of people that just use the random main rules button.
