### ISSUE TITLE
Unplayable randomized main rule settings seed

### ISSUE THREAD

**Issue by joeauty** [TestRunnerSRL/OoT-Randomizer#1019]
Started the game as an adult, closed Door of Time. I don't see a way for me to acquire the 10 skulls needed for the Song of Time. Attached is the spoiler log, and the problems I can see from the spoiler log playthrough:

- "GS Outside Ganon's Castle":                   "Gold Skulltula Token"

I managed to get this eventually, but this is pretty hard.  Shouldn't this be considered a trick that is off by default?

- "LH Grotto Deku Scrub Bombs":                  "Gold Skulltula Token",

I have no way to stun scrubs in grottos as an adult. The playthrough does show `"Kokiri Shop Item 1":                          "Buy Deku Shield",` but  I cannot use the deku shield as an adult

- "Man on Roof":                                 "Gold Skulltula Token",

I have "Man on Roof without Hookshot" selected as a trick, but I can't do this trick as adult link?

-  "DM Crater Wall Freestanding PoH":             "Gold Skulltula Token",

DMC is foolish. I most definitely need this GS token though?

[OoT_9A98E_NUK4O6XW55_Spoiler.json.zip](https://github.com/TestRunnerSRL/OoT-Randomizer/files/4484670/OoT_9A98E_NUK4O6XW55_Spoiler.json.zip)

**Comment by aofengen** [comment]
man on roof without hookshot is supposed to be done as adult. there's a jump specifically for it. the first one is not that difficult and can be done with a backflip or sidehop. Please come to the gameplay-support channel of the discord and we can assist you

**Comment by flagrama** [comment]
Randomized is in fact broken: https://github.com/TestRunnerSRL/OoT-Randomizer/issues/1012

The GS outside of Ganon's Castle isn't too hard. We can show you videos on how to do it in the discord.

You can stun scrubs with your sword. Use a jump attack.

Adult Link can in fact do the side hop. He can also climb on the roof of the potion shop to do this trick.

Gold Skulltula Tokens are foolish as long as your bridge condition is not "Gold Skulltulas". It's annoying I agree, but otherwise there would never be foolish areas.

**Comment by joeauty** [comment]
> man on roof without hookshot is supposed to be done as adult. there's a jump specifically for it. the first one is not that difficult and can be done with a backflip or sidehop. Please come to the gameplay-support channel of the discord and we can assist you

Thanks, I'm happy to be educated, but unless all  4 of these things can be explained, it does appear  to be an unplayable seed?

I usually sidehop from the top of the lookout tower as child Link.

**Comment by aofengen** [comment]
it is not unplayable, as flag just explained (granted it was as you were writing your comment).

**Comment by joeauty** [comment]
Cool, I stand corrected then.

Still, just as a matter of usability, I would still suggest the following coming from a newb's perspective:

- yes I can get the Ganon GS token, and did, but IMO it really should be considered a trick. Getting the man on the roof as child Link is stupid easy yet it is considered a trick. This is more difficult, so why isn't this considered a trick?

- I would consider stunning scrubs without a deku seed or projectile or shield as a trick too. I've watched a lot of OoTR on Twitch and didn't know about this. I don't know how hard it is, but it certainly seems like trick territory because it isn't an intended mechanic.

I guess I'll need to see a video of the man on roof jump to be able to comment on whether I think this should be trick, but I'll fully concede that marking areas as foolish with GS tokens does make sense. It's a bit of a gotcha, but it does make sense when you think about it.

**Comment by flagrama** [comment]
It's really very much preferred that you come to [our Discord](https://discord.gg/ootrandomizer) and ask questions in our #gameplay-support channel to see if something is actually a bug. All of your issues submitted here seem to be a misunderstanding of how something works rather than any actual bugs.

We request everyone do this as we do in fact take great care in how we decide how things work in the randomizer. Most things are done for some reason or another. You're also more likely to get a helpful response there as very few people watch the repo issues, and even fewer bother to answer gameplay-support questions. While in the Discord we have ~40,000 members who can help you with just about anything you're not sure of. You'll get plenty of help there.

**Comment by joeauty** [comment]
> It's really very much preferred that you come to [our Discord](https://discord.gg/ootrandomizer) and ask questions in our #gameplay-support channel to see if something is actually a bug. All of your issues submitted here seem to be a misunderstanding of how something works rather than any actual bugs.
> 
> We request everyone do this as we do in fact take great care in how we decide how things work in the randomizer. Most things are done for some reason or another. You're also more likely to get a helpful response there as very few people watch the repo issues, and even fewer bother to answer gameplay-support questions that pop up here. While in the Discord we have ~40,000 members who can help you with just about anything you're not sure of. You'll get plenty of help there.

Thank you, I'll do this, and my apologies for the false alarm. Is Discord a good place to raise suggestions like mine too?

**Comment by aofengen** [comment]
yes - we have a suggestions channel as well.

**Comment by flagrama** [comment]
Getting the man on the roof is a trick because a casual player may have significant trouble figuring out how to access him. A casual player can see how to get the Ganon GS even if it takes some knowledge of the game mechanics to do it cleanly. (hold the Z-Target button to do a vertical slash while near the edge to kill it, then simply jump off to grab it).

Most people don't do the Deku Scrub with sword because it is in fact easier to do it with nuts or another item. However, again, deeper game knowledge is occasionally needed for the randomizer. A jump attack to a scrub isn't difficult to do once you know to do it. While we try to design the randomizer to be intuitive for casual players, if something is easy enough to do after being explained how to do it, it generally isn't considered a trick. We don't care if something is "intended" or not for tricks. It's more about just how difficult it is to do even with an explanation on how to do it.

**Comment by flagrama** [comment]
Yes, the Discord is a useful place to discuss all aspects of the randomizer.

**Comment by joeauty** [comment]
> Getting the man on the roof is a trick because a casual player may have significant trouble figuring out how to access him. A casual player can see how to get the Ganon GS even if it takes some knowledge of the game mechanics to do it cleanly. (hold the Z-Target button to do a vertical slash while near the edge to kill it, then simply jump off to grab it).
> 
> Most people don't do the Deku Scrub with sword because it is in fact easier to do it with nuts or another item. However, again, deeper game knowledge is occasionally needed for the randomizer. A jump attack to a scrub isn't difficult to do once you know to do it. While we try to design the randomizer to be intuitive for casual players, if something is easy enough to do after being explained how to do it, it generally isn't considered a trick. We don't care if something is "intended" or not for tricks. It's more about just how difficult it is to do even with an explanation on how to do it.

Sorry, missed responding to  this before I closed the issue...

As an addendum, I could have also gotten some deku nuts from Kokiri Forest for stunning the scrubs, so my bad there.

I've moved this to the  Suggestions section of  Discord, closing this issue now.
