### ISSUE TITLE
Playthrough doesn't beat seed

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1044]
Spoiler: https://cdn.discordapp.com/attachments/438698093354156032/724251917295026232/OoT_87AA2_FP2ULUIOQE_Spoiler.json
Plando: https://cdn.discordapp.com/attachments/438698093354156032/724257012501839892/rand-settings.json

This was on roman branch but maybe whatever's wrong applies here as well

**Comment by Zannick** [comment]
I've got a fix, but I need to convert the spoiler to a 5.2.29 plando to confirm it. I can convert the location names fine, just... using a spoiler as a plando file is not easy at the moment.

**Comment by Zannick** [comment]
Okay, the "Child Spawn" and "Adult Spawn" entrances aren't compatible with later versions, and I don't know what all is going on in Roman's fork to be able to fix it. So this should be reproduced with a separate seed, manually constructed or whatever. Or I'll just commit the fix I have and call it done.

**Comment by r0bd0g** [comment]
Can you not partially test the fix on the build the seed was made for?
I'm curious what was the problem exactly? You might be able to recreate the scenario more easily somehow.

**Comment by Zannick** [comment]
Yeah, it fixes on the original build. The problem is as I described it in discord: a Search sphere adds a tod area but no locations, when an entrance is usable with the tod just obtained... Normally, if the algorithm finds an item, that's a signal to keep going, but finding a new tod source isn't an indicator like that. So I'm just retrying the entrances again on tod change.
