### ISSUE TITLE
Temple of Time not accessible from Child spawn

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1053]
BeeLuigiToday at 6:13 PM
https://discordapp.com/channels/274180765816848384/274186223147417600/732702542672298137 5.2.30. Adult start (from randomized settings though I don't know if that's relevant here). Savewarping as child leaves you stranded in graveyard/hyrule castle with no way out.

**Comment by Zannick** [comment]
So we ensure that both ages can reach ToT "at some point in the seed", but the search algorithm is not checking that players go back to ToT after searching locations as a child. The area-based search in a separate branch might help with this, since it maintains a single age per world instead of progressing in both ages simultaneously.

But it may still fail, since it would assume that a player would pick up all necessary items in the spheres prior to reaching ToT, and if they don't...

Either 1) we determine which items are required to reach ToT as adult and ensure that child can reach ToT having gotten only those items, or 2) we ensure that child can reach ToT with only the starting items.

**Comment by r0bd0g** [comment]
I was under the impression that the logic was already enforcing a no-item (or maybe only starting item) route from spawn to temple of time as whatever age you don't start as. One of the comments says:
        # When starting as adult, child Link should be able to reach ToT without having collected any items
        # This is important to ensure that the player never loses access to the pedestal after going child

**Comment by r0bd0g** [comment]
I think this seed had the castle grounds to market issue as well. I don't remember for sure though.

**Comment by Zannick** [comment]
The bug Roman fixed meant seeds expected to bypass the shuffled entrance back from Hyrule Castle, going directly to Market instead. Since Hyrule Castle was involved, this is likely the same thing.
