### ISSUE TITLE
[Suggestion] For Shopsanity No Tunics in castle area and no rupees

### ISSUE THREAD

**Issue by TopHatMan** [TestRunnerSRL/OoT-Randomizer#122]
I think tunics and rupees should be not included in random for shopsanity.

**Comment by TopHatMan** [comment]
If tunic is in castle area you can not buy as kid and you can not buy as adult thats the issue.

**Comment by flagrama** [comment]
Pretty sure that's taken into account in logic. https://github.com/TestRunnerSRL/OoT-Randomizer/issues/90

**Comment by TopHatMan** [comment]
But its not because it keeps showing up up in castle shop the tunics.

**Comment by flagrama** [comment]
But by logic there has to be _another_ tunic somewhere in the world.

**Comment by TestRunnerSRL** [comment]
Yeah unsure if this is something I want to change or not. Rupees sold by shops is mostly just a trolly junk item, but the problem is that they also don't function quite correctly. If I removed them they will always be replaced with some other random junk. For tunics I'm a lot less concerned about them being in shops. I can make is so that the tunics can't appear in a place you cannot buy, but they were put there by design, since there is still a tunic in the world, and the shop is always reachable

**Comment by teallen1996** [comment]
Something I found the other day, and I seem to remember this happening. You can buy the "One time only" tunics as a child. 99% certain I did that, so even if it shows up in the castle shop, it should be gettable.

**Comment by TopHatMan** [comment]
Well thats okay about ruppees but price of ruppee is odd. The tunic is poping up in castle area which should not be right? kid can not buy it.

**Comment by teallen1996** [comment]
The kid can buy a tunic that appears at the randomized price from one of the shops. It is only the default goron (200 rupee) and Zora (300 rupee) ones that can only be bought as adult.

**Comment by csharporblfat** [comment]
1. I could not buy goron tunic from bazar despite having the 200 rupees, said you could not buy it at this time

2. get an ocassional crash with shopsanity, not sure if it is emulator specific, but a save, reset seams to fix it. So may be emulator specific .

3. as far as people saying rupees in the shop are not good, i disagree, the other day I had a seed where I got a 200 rupee for 30, so it was a great deal. Have yet to see it the other way around though, I just wouldn't buy them under those circumstances..

So overall shopsanity seams to be working quite well. I just think the glitch that prevents buying the tunics needs to be fixed.

**Comment by flagrama** [comment]
Was it definitely a "One Time Only" item tunic? Or the vanilla shop tunic? The former should be purchasable regardless of age. The latter will not be purchasable but another tunic should be available in the world. If a "One Time Only" tunic wasn't purchasable then yeah, that's a bug that needs fixed. Otherwise it's working as intended.

**Comment by TopHatMan** [comment]
Its not purchasable as a kid at all no matter what.

**Comment by flagrama** [comment]
Do you have a version, settings string, and seed (and/or spoiler log) that presents this issue for testing?

**Comment by csharporblfat** [comment]
from my experience the tunics were on the right side of the shop, looking at the spoiler there was another tunic somewhere. But regardless of weather there is another tunic somewhere, you should still be able to purchase one if you want.

settings 

5J2Q3JNXC79FAEGA

tunic is in the bazar. going to kakariko as an adult you can get a 200 rupee for just 30 or so.

**Comment by TopHatMan** [comment]
No matter what I do the setting string never works for me and seed will always change so I find it pointless. But I think this happens a lot. I was looking at both branches of Test and Ampharos code. TBH I wanted to play MQ Shopsanity lol. I saw the code that is supposed to stop Tunic from appearing in Castle areas. I do not think it functions at all.



`   # Add adult only checks
            if location.item.name in ['Buy Goron Tunic', 'Buy Zora Tunic']:
                if location.parent_region.name == 'Goron Shop':
                    add_rule(location, lambda state: state.is_adult() and (state.has_explosives() or state.has('Progressive Strength Upgrade') or state.has_bow()))
                elif location.parent_region.name == 'Zora Shop':
                    add_rule(location, lambda state: state.can_reach('Zora Shop Adult Access', 'Entrance'))
                elif location.parent_region.name in ['Castle Town Bombchu Shop', 'Castle Town Potion Shop', 'Castle Town Bazaar']:
                    set_rule(location, lambda state: False)
                else:
                    add_rule(location, lambda state: state.is_adult())`

This is the part right where the check goes.

I am not a python guy so.

**Comment by flagrama** [comment]
Would be easier to read if you used ` ``` ` to surround the code as to preserve the whitespace. As it stands it looks correct to me. It will keep from putting the single chest Goron Tunic in any location you can't access it from.

As for settings string, sometimes new features will break it. Are you using the latest version?

Seed will also always create the same exact layout when provided with the same exact settings and same exact version number.

**Comment by TopHatMan** [comment]
I am sorry here is more detailed info that line of code is in Rules.py and its def function set_shop_rules. It looks correct to me as well. But fact stands the tunics appear in castle area a lot. I am constantly updating the rando but when I try copy my setting string from my files it says incorrect.

**Comment by TestRunnerSRL** [comment]
Wow this thread has had a lot of discussion. I'm going to repeat what I said before.
- The 200/300 tunics on the right side require you to be adult. That is vanilla behavior. The other ones are supposed to be like you got it from a chest and don't have an age check. This is intended. 
- > I can make is so that the tunics can't appear in a place you cannot buy, but they were put there by design, since there is still a tunic in the world, and the shop is always reachable

**Comment by TopHatMan** [comment]
Ok sounds good just confusing.

**Comment by TestRunnerSRL** [comment]
Working on updating the tooltip to try to explain this better, but yeah it's confusing

**Comment by TopHatMan** [comment]
Another good idea for more options would to be add 1-4 buy one items but not shuffle the shop items from each area.

**Comment by TestRunnerSRL** [comment]
Hmm that would be a bit awkward, since you are still removing 1-4 items from the shops, and they might be kinda important to be in

**Comment by TestRunnerSRL** [comment]
Well while it was by design to allow tunics not be accessible as adult from a shop as you might be able to get the second tunic, I changed it so that tunics that require adult can't appear in inaccessibly shops. It guess this caused too much confusion otherwise. It can still happen if you disable "all locations reachable", as it can allow the possibility that some wallets are locked and not everything can be purchased.
