### ISSUE TITLE
Giant's Knife not able to be Foolish

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1311]
It's funny I guess that Knife can't be foolish while Biggoron Sword can.

(Are these items currently used in glitched logic? If so then maybe the foolishness of those items should be conditional based on that setting?)

**Comment by DuskTheUmbreon** [comment]
Yes, they're both used in glitch logic currently.

Glitch logic 1.0 considers them as logically required for the ZD skull.
Glitch logic 2.0 currently considers them required for DoT skip, and very likely will consider them for a few clips in Goron City and elsewhere. It no longer considers them required for the ZD skull, due to the glitchless trick to kill it with a jumpslash and due to the fact that you can just kill it by throwing a pot from OoB.

It'd be very nice to have it made conditionally foolish/not foolish. Especially so that I could later use the same framework to do it with ice arrows.

**Comment by Zannick** [comment]
Yes, we have a framework: check out how we do it for Nayru's, Prelude, etc:

https://github.com/TestRunnerSRL/OoT-Randomizer/blob/ad5f44bda2595fc4803797754957b23d80b30652/World.py#L654-L663
