### ISSUE TITLE
Longshot should be required for completing Gerudo Training Grounds

### ISSUE THREAD

**Issue by joeauty** [TestRunnerSRL/OoT-Randomizer#133]
Hello,

I found a seed where the progress hookshot/longshot was available in GTG, only to obtain this you need the longshot, so I don't think this seed can be completed.

The room where I'm blocked is the large statue room. There is a scarecrow song trigger in this room, but you need to already be above - it is a shortcut for backtracking, but I can't get above without the longshot for the maze room.

Thanks for working on this randomizer, I'm having a blast playing it!

**Comment by flagrama** [comment]
You can hookshot the the target on the ceiling in the left side room with the fire walls and boulders. It requires you to be almost exactly under it, but you can reach it. You can also just let a wallmaster pull you up there if it is your last rupee for the room. From there you'll come to that room from the top floor instead of the bottom.

**Comment by TestRunnerSRL** [comment]
Also if you enter from above as @flagrama suggests, you can void out in the lava instead of needing to make another trip around if you don't have longshot+ocarina.

**Comment by joeauty** [comment]
Sorry guys, I'm an idiot. Totally forgot about the left side room in the maze...
