### ISSUE TITLE
Is skulltula retrievability factored in?

### ISSUE THREAD

**Issue by joeauty** [TestRunnerSRL/OoT-Randomizer#134]
I found a seed where a hookshot was offered as the reward for 30 skulltulas, only the other progressive hookshot was in the BoTW (which was not yet possible to access), and the boomerang was in Ganon's castle.

Is it technically possible to obtain 30 skulltulas without a boomerang or hookshot? I'm just wondering if the logic of the randomizer factors in whether skulltulas can be retrieved?

**Comment by flagrama** [comment]
Open or Closed door? There are the 9 bean patches (excluding the one next to the seller), 3 Skulls in Deku that can pretty much always be grabbed gives us 12. 4 in Kakariko that are also definitely possible up to 16. At least 2 in Lake Hylia you can always get gives us 18. Behind Know-It-All brothers is 19.  The guardhouse skull is 20, the tree by Hyrule Castle skull is 21. 2 Skulls are obtainable in Lon Lon Ranch at any time, 23. The tree in zora river is 24.

If you get bombs you can also add in 3 from Dodongo's Cavern for 27 and one from Death Mountain Crater crate for 28. And the crate in the Bomb maze in Goron City is 29. And the fake wall on Death Mountain Trail near Kakariko Village would be 30.

And for good measure assuming you have the slingshot (or Bombchus) you can get the one on the ladder in Kakariko for 31. The bean patch ones assume you get Bolero and Requiem. If you are missing both then yeah, getting 30 might be difficult in closed door. Open door you might have a couple more dungeon skull options.

Most skulltulas should be in logic since Tokensanity exists.
