### ISSUE TITLE
Guide for Self-Hosting the Web Version

### ISSUE THREAD

**Issue by rehashedsalt** [TestRunnerSRL/OoT-Randomizer#1355]
At present, I can't find any documentation on how to use the code within this repository to self-host a webapp version of the randomizer. It's clearly there -- the Electron GUI is exactly what I'm after -- but I'd appreciate some first-party documentation on setting it up.

Reason being, I would like to self-host a version of this application for use within my friend group. OoT Multiworlds have become a regular thing for us, and spinning up my own app looks appealing for the following reasons:
* It takes load off the main server
* It's more resilient to takedowns
* I want to archive all the seeds we generate
* I wanna put it in a container for fun and profit
* I'd like to experiment with automating the seed-creation process (though I guess this is totally independent of the frontend, the more I think about it)

I'm well-versed in webserver administration; I just need enough of a guide to get to "this service hosts the randomizer on this port". Everything after that I can handle myself (and is probably out-of-scope for this project anyhow).

**Comment by TreZc0** [comment]
Sadly, the server code for the web app is currently not open source. Ootrandomizer.com has become a very complex and big eco system due to keeping a compatibility layer for older versions, a non public api for special use cases, and the integration with all kinds of services.

Sadly, due to the fact that this is a mere two person project, we currently do not have the resources to clean up the gigantic codebase below it, which comes with a completely independent node.js webserver spawning the python processes of the Randomizer on the backend.

So at this point in time, there's sadly nothing I can offer, I'm sorry.

**Comment by OriginalPiMan** [comment]
Aside from putting it in a container for fun and profit, couldn't you get almost the same result from just using the download/offline version?
The load is off the server
It can't be taken down
You can archive everything however you want
And you can automate the seed creation process.

**Comment by TreZc0** [comment]
Not quite. Remember the features we have that make patch data available for example. 
There is a full fledged psql database running behind the server, allowing access to old seed patch data. Then there's the encryption stuff using a non public branch of the Randomizer, the differentiation between master and dev, the challenge seed stuff and more. The website just uses the Randomizer source in a ton of different ways, but the output is handled very differently, especially since saving original copyright protected data like the original or patched rom is not an option.

**Comment by rehashedsalt** [comment]
@OriginalPiMan I could; most of the functionality I want could be obtained by just wrapping the CLI version and chucking some stuff in a DB. But since the Electron frontend pretty well matched what was on ootrandomizer.com, I was mostly curious if there was a switch or something I could add to make it web-friendly.

Sorry to hear about the massive tumor in the stack. I'm not exactly a seasoned developer, and I totally understand the need for secrecy around competitive keygen, but I'd be happy to assist if there's any interest in untangling it.

**Comment by TreZc0** [comment]
Currently not planned any time soon :/
