### ISSUE TITLE
AGR doesn't work with ER

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1475]
I'm not sure of the specifics, the bug maybe hasn't been confirmed yet? I'm opening an issue so that people are aware of a potential problem.

**Comment by r0bd0g** [comment]
This message https://discord.com/channels/274180765816848384/704998094370111538/928050443374968922 describes the possible issue.

**Comment by mracsys** [comment]
More details:

The goals are defined before regions, so it doesn't know if a dungeon is unreachable at that point. For ER, world validation only has a check for ALR or AGR/BO+beatable game, not AGR+beatable game+beatable goals (see https://github.com/TestRunnerSRL/OoT-Randomizer/blob/84696bf88642e02418704f7b9535a483a8e2edae/EntranceShuffle.py#L727-L735). Then in Fill, `predicate` (https://github.com/TestRunnerSRL/OoT-Randomizer/blob/Dev/Fill.py#L395) will always be false because a goal is permanently unreachable, which makes `perform_access_check` always true, which makes a location a valid fill only if it's reachable (https://github.com/TestRunnerSRL/OoT-Randomizer/blob/Dev/Location.py#L77), which is why we still get beatable games even if goals are unbeatable.

Spoiler from the original report is attached: [OoT_B7920_VOG8F5WX3J-3_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/7811144/OoT_B7920_VOG8F5WX3J-3_Spoiler.txt). Water Temple is in Lon Lon Ranch open grotto, which is only accessible as child. Bridge is any 3 dungeon rewards, which makes every dungeon a goal. Since adult can't enter the grotto, and warp songs/spawns can't take him there, Water Temple is permanently inaccessible.

**Comment by r0bd0g** [comment]
Apparently AGR for tokens not being locked by token bridge isn't working either? So something else also seems wrong.

**Comment by fenhl** [comment]
> Apparently AGR for tokens not being locked by token bridge isn't working either? So something else also seems wrong.

I opened #1719 for that since it's not related to this issue.

**Comment by r0bd0g** [comment]
Recent report suggests this issue has not been fixed.
