### ISSUE TITLE
Support GUI for Apple Silicon chips (M1)

### ISSUE THREAD

**Issue by RawZ06** [TestRunnerSRL/OoT-Randomizer#1544]
Hi, the current version of GUI cause some problems.

- Actually the version of electron is not compatible with M1 chip and the GUI start with Rosetta only with node 14. 
- `node-sass` has the same issue.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/44646690/160254884-a18130da-9ee9-48c2-b45c-2c6c922832a1.png">

I created this issue to know, and everyone knows what is the plan to support M1 chip.

**Comment by Cuphat** [comment]
Unfortunately, this is not something that will be able to get fixed easily. The GUI is at a weird spot with some of its dependencies where updating them means updating a lot of things and will require a lot of code to be rewritten. When that rewrite is done, the GUI will be able to support more recent versions of node. As far as I know, once that happens, native M1 support should just work since the updated packages should support it. I'm not sure what the timetable is for the GUI update, though.

**Comment by RawZ06** [comment]
Thank for you response.
It would be possible to use old tkinter GUI in option (for example --legacy) if we have some difficult to use electron based GUI ?

**Comment by cjohnson57** [comment]
No, the old GUI wouldn't have all the things that have been added since

**Comment by TreZc0** [comment]
A TKinter GUI is not even remotely possible, yea. The old GUI, for lack of a better term, wouldn't even come close in feature parity, besides the fact that there is no desire to maintain two GUIs.

Currently, anything above Node 14 is not supported on Windows either for the same reasons pointed out above.

Sadly, the GUI was designed on a version of the templating framework Nebular that got many major and breaking changes with a new version right after release. An update, which would be required for NodeJS v16 support, will require a major Angular bump as well.

All of this is planned for later this year, but rn, i cannot give a detailed timeline.
