### ISSUE TITLE
"Pre-planted Beans" setting does not show in the spoiler log if main rules are randomized

### ISSUE THREAD

**Issue by ETR-BTF** [TestRunnerSRL/OoT-Randomizer#1576]
https://discord.com/channels/274180765816848384/438698093354156032/977400893945298964

**Comment by fenhl** [comment]
The issue here seems to be that “Randomize Main Rules” includes this setting but does not disable it. Depending on whether including the setting in “Randomize Main Rules” is intentional or not, the fix would either be to add it to the list of settings disabled by “Randomize Main Rules”, or to remove the `randomize_key` GUI param from it.

**Comment by ETR-BTF** [comment]
It shouldn't be included in "Randomize Main Rules" because it's in the "Other" tab. That said I wonder if that really is the best place for it. It's a timesaver, yes, but it also has logical implications. But I guess so do Skip Child Zelda, Complete Mask Quest and Free Scarecrow's Song.
