### ISSUE TITLE
MQ Multiplayer - Message and Text issues

### ISSUE THREAD

**Issue by friedpen** [TestRunnerSRL/OoT-Randomizer#163]
Pooling a bunch of text issues together as to not spam issues.

1. Custom text does not display a Player tag. This occurs with the new MQ hints for Compasses/Maps as well as the Tycoon's Wallet. Not too game breaking but it can be confusing when a player with wallet 500 receives a progressive wallet for another player as it will just state 'you received tycoons wallet'.

2. MQ Compass/Map hints display for both players. If you are Player 2 and receive a Compass for Player 1, both players will be able to see which medallion/stone is in their dungeon. For example it may say 'Compass for Fire Temple ... Water Medallion' on the screen for Player 2 when they pickup the Compass. Then when Player 1 receives it, it will states 'Compass for Fire Temple ... Zora Sapphire'. Not sure if this is fixable or if it should just be a feature for information gathering.

3. Issue #98 is back if full sanity, including shops 4, is done in coop with MQ hints enabled. I can recreate the settings/seed if necessary but I believe its just the introduction of new compass/map text alongside coop shops 4.

4. Ganon's Castle Boss Key does not appear in Dungeon Info display. Don't know if this has been reported as it may already be part of a pending fix.

Small side question, is it possible to close rooms in the multiplayer script? I've had my internet cut out twice and those rooms are still lingering in the list.

**Comment by TestRunnerSRL** [comment]
1. Should be fixable
2. Hmm that might be hard to fix.
3. Ehh, it's becoming harder to fix this issue without deleting vanilla text
4. Probably a bug.

I think all in all, that I probably won't really be able to get it to behave quite correctly for coop. The best solutions I can think of is that the items do not have special text and you just have to check the dungeon menu after getting the item, or that the option just isn't allowed in coop. The way it's implemented would make it hard to have the text not give away info for the wrong player otherwise

**Comment by TestRunnerSRL** [comment]
Also for deleting rooms, You can host the room with the same password, and then close it. I kinda want to put something for making it auto clear idle rooms, but yeah dunno

**Comment by TestRunnerSRL** [comment]
1-3 should be ok for now, fix for 4 is on the way

**Comment by TestRunnerSRL** [comment]
This is fixed in the MQ branch now
