### ISSUE TITLE
A setting to disable to use of major glitches.

### ISSUE THREAD

**Issue by Psychochria** [TestRunnerSRL/OoT-Randomizer#1734]
Though I am a Glitchless fan, and definitely see the hypocrisy of allowing some glitches in the category, I would love to see some of the major glitches used in speedruns to be togglable as "fixed" for use in some randos. Getting some famous runners to race without the use of hessing, equip swap, QPA, etc. would be really interesting to see, especially when combined with randomization.

A basic list could be taken for the rules of the [Glitchless category](https://www.speedrun.com/oot#Glitchless) on speedrun.com.

Just an idea that could spark discussion, and one that I know would require a ton of work.

**Comment by DobbyDigital** [comment]
As someone who prefers to use glitches, I don't really see a reason for a setting like this.  None of the glitches you mention can be performed accidentally, and so such a setting can be easily reproduced by the players following a given ruleset. 

Additionally, the motivation you give is to see "famous runners [race] without the use of hessing, equip swap, QPA, etc.", however the players who use glitches are choosing to do so because they prefer playing that way. Why force them to play in a way that is less fun for them?

**Comment by Psychochria** [comment]
> 

I'm not forcing anything! It'd just be an option when creating a rando.

**Comment by DobbyDigital** [comment]
What would be the point of the option though? If you prefer to race without glitches, that can be agreed upon by the players. An option like this would require a great deal of work, for very little benefit.

**Comment by aofengen** [comment]
This is not something that will ever be a part of the randomizer. What you're asking for is forcing a ruleset change into the randomzier itself, which is pointless given that those sorts of restrictions can be accomplished by the player just not performing them.

**Comment by fenhl** [comment]
There are players who would not agree to not using glitches as a ruleset change but would play with this setting as a challenge.

**Comment by aofengen** [comment]
I'm not suggesting changing any racing ruleset. But I don't see the point in creating the option when all you have to do is jot use glitches, if that's what you want

**Comment by cjohnson57** [comment]
Yeah, there's no reason for this to exist, sorry. Patching some vanilla glitches would be non trivial including changing how the engine's physics work and you can just choose to not do them.
