### ISSUE TITLE
Seed fails to generate

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#174]
https://imgur.com/RCEYZLJ

Version: 2.18.8
Settings: 9JAKABAAADJJGBAJB

Seed unknown. Happens "every now and then" with multi-world seeds, apparently.
Report from Raikaru.

It seems the item in one of the always required hint locations is none for some reason...

**Comment by r0bd0g** [comment]
https://cdn.discordapp.com/attachments/438698093354156032/493897424830464012/unknown.png
https://cdn.discordapp.com/attachments/438698093354156032/493894913327366155/unknown.png

Ignoring the errors, I find that song from saria is nothing in that first seed, and song from oot is nothing in that second seed. Normally if locations are empty it raises a fill error, but that fill error doesn't check special locations like songs. Songs are supposed to retry if they fail to place, but if the game is beatable anyway it doesn't bother to. Something like that? That's my guess as to what's happening.

**Comment by TestRunnerSRL** [comment]
It used to not throw errors for empty locations but it threw errors for excess items. In the first situation, the seed is not valid and cannot be generated. In the second the seed might be ok depending on what items are missing, but is a bit of a red flag as this should never happen. So initially this was backwards and considered switching it back, but I decided to just throw an error either way as it should never happen, and if it does it means something is wrong with the code. As far as the can_beat_game in the fill, it should probably be removed. Generally if you get to that check, there's something really wrong with the seed and you should just be told immediately. Technically it might be ok to implement some kind of system so that it'll auto-fill missing locations with junk if the game is beatable, but that is probably not something people would like if major items have a chance to be missing.

As far as multiplayer, not sure. Might be because it might be easier to have this situation happen, but I kinda doubt it's multiplayer only.

**Comment by TestRunnerSRL** [comment]
I removed the check so it should be fine now
