### ISSUE TITLE
[Suggestion] Logically require Map+Compass for dungeon's boss in Keysanity

### ISSUE THREAD

**Issue by henriquegemignani** [TestRunnerSRL/OoT-Randomizer#185]
Idea from the LttPR.

When the Map+Compass in shuffled outside of the dungeon, consider that the boss logically requires the Compass. This guarantees the compass will always be obtainable before having to finish a dungeon. This increases the likeliness the Medallion hint will be useful and potentially provides additional information if you're sequence breaking.

Another option would entering the dungeon logically requires the Map.

**Comment by TestRunnerSRL** [comment]
This restriction always felt relatively arbitrary in LTTP since there's only the map is only telling you about one of the two rewards from the boss anyways. It makes the map info generally really low value if you're already diving, and generally speaking you probably will if chest value is good. Most players will dive/beat the dungeon regardless if they have the map, since it's not the case that not having the map means you can't beat the dungeon, since it might be accessible without collecting any items somewhere you haven't checked or maybe it's not. Basically it means, that while it's nice to guarantee the info exists before beating the dungeon, it is usually a bad play to actually rely on it, and it just bogs down the logic. 

There's a couple dungeon where having the info can pay out, but it's not common. Basically you need to have all the non-dungeon items and the map. Which can happen, but again it just makes the value low, and unless the dungeon is a huge pain to get to the boss (like MM), then you'll beat the boss to avoid the chance of a double trip and it's a pretty bad gamble to skip seeing as 7/10 o the dungeons are crystal. OoT is a pretty much the same as LTTP in this regard.

As for needing the map to enter the dungeon at all, it's works a bit better, but the info becomes bad for a different reason. Just because you know a dungeon is medallion, does not affect whether you need to enter the dungeon, so you'll still route around chest value anyways, and ignore whether you have the map. And as before if you "sequence break" a map/compass, it's hard to gain info about it since they were quite possibly available but in a remote location.
