### ISSUE TITLE
softlock when playing SOS in windmill

### ISSUE THREAD

**Issue by csharporblfat** [TestRunnerSRL/OoT-Randomizer#186]
everything sanity, version 2.20.2
settings and seed

5J2Q32PXK4SB3EAAHA

9ELXJNZ9UI

windmill animation plays, then black screen. 

interesting solution, if it is night time when you do this it softlocks, however if it is daytime it does not.

Can anyone else recreate this?

**Comment by r0bd0g** [comment]
This crash is a known pj64 issue.

**Comment by flagrama** [comment]
This is caused by having an existing vanilla save file before loading rando, and Project64 not recognizing rando ROMs as OoT ROMs and setting the appropriate settings since they check the CRC of the ROM to activate them.

As of Project64 v2.4.0-1161-g18d1867 this issue can be solved for all rando ROMs on PJ64 by going to Options > Settings > Options and unchecking "Hide advanced settings" going to Options > Settings > Options > Defaults and checking "Protect Memory"
