### ISSUE TITLE
Mask of Truth's hint's conditional always outdated

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1923]
If the full trade quest is shuffled, claim check may be just freely available to turn in, which makes the difficulty of check no different from when trade quest shuffle is off but claim check is the only possible starting item.

You should double-check Mask of Truth as well to make sure it still makes sense.

**Comment by fenhl** [comment]
Biggoron has been fixed in #2025. The current conditional for Mask of Truth is:

https://github.com/OoTRandomizer/OoT-Randomizer/blob/5dfd0d24f63e06bad319ab240763c273d61f6319/HintList.py#L218

So it also needs to be adjusted for child trade shuffle. Let's repurpose this issue for that. @r0bd0g could you update the issue title please?
