### ISSUE TITLE
Usability feature to rotate the camera left/right with DPad

### ISSUE THREAD

**Issue by geekley** [TestRunnerSRL/OoT-Randomizer#1984]
OOT has aged quite well, except for one VERY annoying thing: **Camera Controls**. Controlling camera only with Z has limitations which make gameplay less fun, and it's hard to go back after getting used to modern games which have this feature. See how the camera works in Twilight Princess, for example.

If I'm not mistaken, DPad Up is not being currently used, correct? So, here's my proposal to make the D-Pad much more useful.

### DPad Left/Right: Rotate camera clockwise/counter-clockwise
Just rotate the camera around the vertical axis. Although the axis control is digital, this should ***NOT*** work like in Mario 64. It must be similar to how it automatically rotates after a while when Link is not facing forward -- except it goes where you want instead of forcing forward direction. This manual rotation should also behave well together with this auto-rotation.
- The timer until this auto-rotation happens should be reset after manual rotation. Or better, it should be disabled, and reset only after Link moves.
- Rotating at constant speed is not the best implementation. It should quickly (< 1s) accelerate until that max rotation speed, so it "feels nice" to use. When releasing the button, let it decelerate too instead of stopping instantly. I.e, it must be "smooth" and have good usability for both tiny/fine and large/coarse rotations.
- Respect circumstances where the camera is not allowed to rotate. Though a great implementation would allow some rotation when Z-targeting too, to improve control during battles.

In any case, it must always feel right, nice to control and intuitive.

### DPad Up: Toggle what Link is wearing
For Child Link, this would toggle Bunny Hood if it has Majora's Mask behavior; otherwise, toggle between Deku Shield and Hylian Shield.

For Adult Link, that would toggle boots.
There are some alternatives for how this can be implemented (ordered by what IMO is best first).
1. **Toggle auto-selected boots**: If Link is underwater, D-Up toggles between Normal and Iron Boots. Otherwise, it toggles between Normal and Hover Boots. This is only when you have both -- otherwise you just toggle between Normal and the other one. This context-dependent logic provides the best usability; but I don't know if there's glitches that would be less practical with that -- probably not an issue (?).
2. **Cycle through boots**: D-Up cycles between the boots that you have; possibly between all 3: Normal > Iron > Hover > Normal > ... -- a tradeoff for a somewhat good solution overall, and shouldn't be hard to implement.
3. **Toggle last used boots**: Selecting Iron/Hover boots manually in the Equipment Menu Screen sets which boots D-Up toggles. So it toggles between normal boots and that one. You could even expand this to include swords too (so when setting a different sword, D-Up now swaps swords).
4. **Set D-Up equipment**: Works like C buttons -- press D-Up in a sword or boot to set it to D-Up. This may need some special UI to show the player that it can be done, so maybe not the easiest to implement. Might be overkill.
5. **Toggle camera rotation**: D-Up toggles the behavior of D-Left/Right between camera rotation and equipping boots independently. I don't like this solution, but it's a possibility.

### DPad Down: Ocarina
No changes needed here.

**Comment by DuskTheUmbreon** [comment]
D-up cannot be used because it's already assigned to something on VC.

> RandoBot
BOT
 — 05/20/2023 6:50 AM
Due to VC players having fewer buttons to work with, D-Up serves in the place of an N64 L Button (since Z is bound to the left trigger button on Gamecube and VC controllers). 
Since parity across all platforms is an extremely high priority for this project, D-Up will remain reserved for VC's needs.

**Comment by fenhl** [comment]
The D-up button will not be used because it's not available on VC. (The Wii's D-up button is mapped to the N64's L button.)

**Comment by geekley** [comment]
Ah, I see. I didn't know that.
You could still make it a randomizer setting, for people who won't play on Wii VC.

And toggling map is not more important than camera control IMO, as long as map is enabled by default. (Unless L has another use I'm not aware of...?) So, in this case, you could make an option to equip on L instead of D-up, so VC players would benefit from camera control too if they're fine with giving up the map toggle feature.

**Comment by DuskTheUmbreon** [comment]
As mentioned in the bot post I quoted, platform parity is almost certainly never going to be violated. If a feature isn't possible on one platform, it almost certainly will not be added, as a setting or not. Especially not something as massive as rewriting how the camera works.

Toggling the map is a vanilla feature, and is useful for people more associated with the speedrunning scene. Buttons to rotate the camera, imo, aren't nearly important enough of a feature to justify removing a vanilla feature, no matter how small it seems. Especially since learning to manipulate the camera well is a rather important skill and is vital to various setups.

Not to mention the fact that camera is controlled through one of the most complex and convoluted files in the game. This would almost certainly be an incredibly complicated change.

**Comment by geekley** [comment]
> This would almost certainly be an incredibly complicated change.

Sadly, I must agree with you.
And it's unfortunate that this isn't available even in OoT 3D, [apparently](https://www.reddit.com/r/Citra/comments/9k1zur/camera_control_in_oot/) because it was made before the 2nd stick accessory thing (dunno about randomizers for OoT3D).

**Comment by r0bd0g** [comment]
"See how the camera works in Twilight Princess, for example."
My version of TP actually doesn't have this feature, as far as I can recall.

**Comment by geekley** [comment]
@r0bd0g I'm pretty sure it's only in GameCube version.
