### ISSUE TITLE
Trial/Poe Count setting affects seed even when Random Trial/Poe Count is selected

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#206]
For example D2L2Y9PX3LAFSEAEDA is the settings string for 2 trials, with random trial count enabled.
For example D242Y9PX3LAFSEAEDA is the settings string for 6 trials, with random trial count enabled.
They should probably be considered different aspects of the same setting.
The spoiler log would also have to be changed to only display the number of trials if the number is not random.

Also applies to maps/comps give info.

**Comment by TestRunnerSRL** [comment]
This was something that was originally by design. If you're sharing settings, it would be with the setting seed anyways, so it's not really an issue. Making the setting string not have the disabled options would have some problems, since you would lose settings. Unsure what the best approach for this, but as is, it's not really a bug.
