### ISSUE TITLE
Fast Epona doesn't check for ocarina buttons before spawning Epona

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#2065]
She's not supposed to spawn outside ranch until you're able to actually play the song. Checking for only Epona's Song and Ocarina isn't enough anymore.

**Comment by DuskTheUmbreon** [comment]
Is it possible to just keep her below the map until the player first plays epona's song?

It'd fix both this issue *and* being unable to use OI to call her, while future-proofing for any other potential changes.

**Comment by Natheirean** [comment]
Shouldn't it just be not logical to use Epona until you're able to play the song? Like still spawns if you have Epona's Song & Ocarina, just not logical to use her for checks like crossing the bridge without the notes for it

**Comment by Natheirean** [comment]
I think not having her spawn at least w/o song notes would be a flag level change if I'm reading the files right, which I'm not confident in trying like I was thinking at first lol

**Comment by GSKirox** [comment]
It is not logical to use Epona until you're able to play the Song.
But r0b is right in that she should not spawn at Ranch in that case, since rando already checks for song/Ocarina before spawning her.
I'm working on a fix but this change is done in ASM and i'm pretty bad at it 🚶

**Comment by r0bd0g** [comment]
She's not supposed to spawn until you can play the song -- that's why we check for both the song and ocarina already rather than just letting it happen. There are potential non-repeatable access issues if you go and get your horse stuck somewhere.

**Comment by MajikVroom** [comment]
@GSKirox @cjohnson57 please reopen.

The changes in #2066 aren't fully effective due to alignment issues with EPONAS_SONG_NOTES. EPONAS_SONG_NOTES is supposed to be 0x1A by default (i.e. requires notes U L R). But because the variable isn't aligned in config.asm, it got placed at unaligned offset 80401323. When can_spawn_epona reads it, the generated code doesn't account for the lack of alignment (or throw a linker error, I guess), so it only ends up reading part of the value: 0x1. The net effect is that with the current alignment, can_spawn_epona returns true as long as you have the A button; with different alignment, you might see different results.

Proof: In the Bizhawk debugger, I saw that the instruction loading from 80401323 got the value 1. To confirm, I put the A button in starting inventory, and Epona spawned in the field. I put the U L R notes in my starting inventory, and she did not.

I'm not sure of the process for making C/asm code fixes, and also don't particularly want to set up those tools on my laptop since I'm traveling at the moment. That's why I'm just leaving a comment instead of actually fixing it myself.

**Comment by MajikVroom** [comment]
This can lead to unbeatable seeds, by the way. If logic lets you get the notes for Epona's song but not the A button, then you'll be able to play Epona's song but it won't do anything. My rough understanding is that this code is basically suppressing the "I rescued Epona" flag to keep her from appearing in the field.

**Comment by GSKirox** [comment]
Can reproduce. I'll try to see what's going on today.
