### ISSUE TITLE
Frogs 2 misc. hint requires reloading area to reread

### ISSUE THREAD

**Issue by fenhl** [TestRunnerSRL/OoT-Randomizer#2125]
If you accidentally mash through the frogs 2 misc. hint, you have to reload Zora's River to read it again. (Entering and exiting a grotto works.) This can be very inconvenient. Unsure what the best way to fix this would be.

**Comment by r0bd0g** [comment]
I think that's normal and not a bug. The textbox that was used is only supposed to appear the first time on each area load.
Does reloading the room only work? (As in, go up by the waterfall and come back.)

**Comment by fenhl** [comment]
It's vanilla behavior but that doesn't make it not a bug.

**Comment by Natheirean** [comment]
Is it possible to move the text box to when you pull ocarina out instead of when you stand on the circle?

**Comment by r0bd0g** [comment]
One idea to fix this issue is to, idk, add a sign nearby you can just read, says what the frogs hold. But I think this misc hint was added b/c the text box was right there and it was easy enough to just have it say it. The hint would otherwise just be out on a gossip somewhere. So are we also adding signs out by the moat that says what the OoT/SoT checks are? I feel like any additional hack that makes this text rereadable kind of defeats the purpose, where we had an otherwise quick and easy way to hint this check. It wasn't supposed to be complicated. I think if you want something better you should be prepared to have a more general solution, like adding signs near every always check or something, or adding a pause menu where you can reread all the hints you've read idk.

**Comment by r0bd0g** [comment]
I ran the test myself since I didn't get an answer. Going up to the top area of the river does refresh the textbox. So you don't actually have to take any loading zone to some other area.

I want to say also, the actual worst textbox to mash through and not read is the Ganondorf light arrows hint, which takes a couple minutes if you need to read it again. (I did an async a day or two ago where I forgot to read it lol. But luckily I was able to dig what it said out of my subconscious.)

**Comment by fenhl** [comment]
Can we reset the trigger for the text box when Link steps off the log and back on? That seems like a solution that wouldn't feel as out of place as adding a sign.

**Comment by jdunn596** [comment]
> Can we reset the trigger for the text box when Link steps off the log and back on? That seems like a solution that wouldn't feel as out of place as adding a sign.

I was thinking this would be the best solution honestly.

**Comment by r0bd0g** [comment]
I'm not sure how that would interact with somebody trying to use OI to do the frogs. A person doing that would probably have to read the text every time?
