### ISSUE TITLE
Bug: Silver Rupee Text Box causing crashes

### ISSUE THREAD

**Issue by JQuilty** [TestRunnerSRL/OoT-Randomizer#2162]
I did a seed yesterday with randomized silver rupees and pouches, confined to zones. In BOTW's basement, the silver rupee instance you get when you climb the ladder put up a text box that would then cause the game to softlock because Link would be frozen on the ladder (the actual game still running). This also prevents you from getting to the check at the top of this climb that leads back to the main floor. This is the same vanilla game issue that can occur in Zora's Domain if the diving rupee game timer expires while Link is on the ladder leading to the entrance. The exact check from the spoiler log:

`"Bottom of the Well Basement Silver Rupee Ladders Middle":              "Silver Rupee Pouch (Bottom of the Well Basement)",`

Logic for silver rupees should disallow this check from being something that puts up such a text box. This happened with a silver rupee pouch that was for the BOTW basement, unknown if it would happen with, say, Shadow Temple silver rupee pouch. I have not observed this behavior for regular items. Like the Zora's Domain instance mentioned above, both involve a camera perspective change.

**Comment by JQuilty** [comment]
[OoT_F2BAF_770J62J36A_Spoiler.json](https://github.com/OoTRandomizer/OoT-Randomizer/files/13926826/OoT_F2BAF_770J62J36A_Spoiler.json)

Spoiler log in its entirety if settings info is needed.

**Comment by fenhl** [comment]
The thing that causes the softlock is not the text box but the cutscene. See also #2004. This specific instance is more severe due to the possibility of making the seed unbeatable as you said. This was actually discovered in December (see Discord conversation starting [here](https://discord.com/channels/274180765816848384/438698093354156032/1186614966434938970)), and two fixes proposed then were to move this check so it's not on the ladder anymore or a placement restriction like you suggested.

**Comment by JQuilty** [comment]
@fenhl I see, I checked the bug reports for silver rupee issues and didn't see any, I didn't know it was already known. But it sounds like either one of those will work as a fix, moving it to off to the level surface or forbidding it from being a pouch/silver rupee for that room.

**Comment by fenhl** [comment]
It was only reported on Discord and then forgotten about, so it's good that you opened this issue.
