### ISSUE TITLE
Removing/Nullifying heart drops and fairies

### ISSUE THREAD

**Issue by phixtyseven** [TestRunnerSRL/OoT-Randomizer#233]
This is really something I've been wanting to try to do myself, but I have no idea how to approach it. I think I'm looking for the functions that modify the player's health. Are there specific resources or tools that would help me figure out what I'm dealing with?

What methodology do those of you who regularly operate on the game code use? How do you disassemble the ROM; how do you pinpoint relevant addresses; etc?

Any help is very much appreciated :)

**Comment by r0bd0g** [comment]
There are locations (at least one, but also some vanilla-intended routes as well) that will become logically impossible if fairies do not work in ohko.

**Comment by phixtyseven** [comment]
I was intending to create a separate difficulty option (if things came together nicely), but that is good to know.

**Comment by TestRunnerSRL** [comment]
This might be somewhat simple to implement, since this is probably handled in the same place I implemented OHKO. For finding the relevant code, I usually use Bizhawk's debugger and set a break point on when link's health changes. From there I look at the surrounding code to figure out what it does.

It's possible that this will be extra tricky since something might try to keep healing until you are max hp, and if you keep negating the heal that you'd softlock. Unsure, it really depends on how these kinds of things are implemented in OoT.

**Comment by phixtyseven** [comment]
@TestRunnerSRL Wow, thank you! This seems to be just what I've been looking for.

After spending some time putting it together and playing around with it, I've gathered a few things:
* lua scripting requires interpreted emulation (makes sense :P)
* breakpoints can be made when addresses are read, written to, or executed (or you can script them in)
* current_hp is stored in address 0x80011a600; 2.5 hearts = 0x0028...
* current_hp is modified from multiple instructions (may be incomplete or inaccurate):
  * 0x80072148 heal 1h/take damage -- harm, heart pickup, poe bottle harm
  * 0x8007215C heal <1h -- heart pickup, any free fairy (immediate full heal)
  * 0x80072184 drop to zero -- harm
  * 0x80078598 heal >=1h -- piece, fairy bottle, poe bottle, ...
    * Repeats (t1 counts down from 20, 3, 1, ...)
    * Also triggered by start of fairy bottle heal even if <1h to heal. Heals nothing, then causes 0x800785F4
  * 0x800785F4 heal <1h -- piece, fairy bottle, poe bottle

So I guess the next step is to follow these instructions upstream, find out what addresses values are being loaded from, locate the values in ROM (hopefully the same RAM/ROM offset as the instructions themselves) and hard-code the values in Patches.py? What are the symbols listed in ASM/build? Should I concern myself with those? Thank you again!

**Comment by TestRunnerSRL** [comment]
The location in rom are their location in uncompressed rom. When the asm code make references to locations, they are location in ram. OoT uses a VRAM system, so the locations are going to be ok if you reference things within the same file or if you read from places that aren't repointed into RAM and are always loaded. So the main code file in OoT is always in a fixed place, as well as the save context and link's context. But various actor files might not be, so it's a bit tricky to have files reference each other. If you are modifying rom and changing the code that gives you health, then it's less of an issue since the rom doesn't change. But it would be a problem if you're trying to cause this to happen with some lua script at run time.

**Comment by TestRunnerSRL** [comment]
the ASM/build files are generated when the ASM/c files are compiled, so you don't need to mess with it at all. They aren't used again afterwards, and their existence is mainly for debugging purposes after the fact.

**Comment by phixtyseven** [comment]
Should have closed this a while ago. I will work on this more sometime in the future.
