### ISSUE TITLE
Map&Comp Info on, but Altar still gives info

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#246]
BladefangFT Today at 3:21 PM

maybe found a not intended behaviour with M/C give information? 
version 3.0 setting: R4CKAPSPP6CLA3992T seed: STMMXV65QY
temple of time altar still says where stones and medaillions are, but it does not add them to the overlay.

---

The last minute-change to allow map&comp info regardless of m/c placement must not have been implemented correctly.

**Comment by flagrama** [comment]
> This setting, only available if you start with Maps and Compasses or they are spread across the world, disables the pedestal in the Temple of Time from giving information about
the location of the Medallions and Spiritual Stones.

Looks like it only has an effect if you select Maps/Compasses: Anywhere.

It doesn't make sense for it to work with those settings (Maps/Compasses: Dungeon Only) anyway since you'll already know if it is MQ or not, and have already taken the risk of entering so the information won't change your mind. Makes sense to keep it on altar in this case.

**Comment by r0bd0g** [comment]
The readme I guess was also not updated to reflect that last-minute change.

**Comment by Cuphat** [comment]
I noticed this as well. It seems the altar will still give information unless Maps/Compasses are set to Keysanity along with Enhanced Maps/Compasses.

https://github.com/TestRunnerSRL/OoT-Randomizer/blob/c1c4fc7a766d1c807aa300b45cb5b21686481e57/Patches.py#L1438
https://github.com/TestRunnerSRL/OoT-Randomizer/blob/c1c4fc7a766d1c807aa300b45cb5b21686481e57/Patches.py#L1487-L1491
