### ISSUE TITLE
Bug in the logic regarding DM Trail Freestanding PoH and OHKO

### ISSUE THREAD

**Issue by BeeLuigi** [TestRunnerSRL/OoT-Randomizer#264]
As it is right now, the DM Trail Freestanding PoH is in logic if Open Gate is selected (and maybe through other means too) even if the difficulty is set to OHKO, without any other requirements. See the spoiler log attached for an example where the PoH is in sphere 1 of the playthrough with OHKO selected. Looking at it's section in Rules.py, it definitely seems to be an actual logic bug rather than a spoiler generation bug.
[OoT_9LARSJBLKAAAUKAA23_VVI1BQ8VMP-9_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2568982/OoT_9LARSJBLKAAAUKAA23_VVI1BQ8VMP-9_Spoiler.txt)

**Comment by r0bd0g** [comment]
Child Link can backflip down to the heart without taking damage if you angle it right. This is intended logic. (Actually adult can avoid damage with a backflip as well by using the hookshot halfway down to shorten the flip, but that's kind of too far to be in logic.)

**Comment by BeeLuigi** [comment]
Ah, so the reason the section in Rules.py looks so weird is because there's different requirements for Child and Adult I guess? That makes sense, thanks!

**Comment by XerShade** [comment]
Another thing, if you have access to river and adult the logic will assume you can plant the magic beans and get the POH the intended way. (The attached spoiler log won't load for me, I'm just going to assume you didn't have access to explosives to get beans or plant them in that patch. Just a tip a lot of people miss/forget about as beans are generally useless.)

There have been times where I've gotten "stuck" because I didn't have an item to do a trick to skip a magic bean, and didn't want to waste rupees on them but the randomiser was expecting me to use the beans.

**Comment by r0bd0g** [comment]
The bean to get the DMT PoH is not logically relevant. Again, child Link can backflip down without taking damage. If you can plant the bean, then you can get there as child. So it won't be checking if you can access river.
