### ISSUE TITLE
Free scarecrow song bugs

### ISSUE THREAD

**Issue by Hamsda** [TestRunnerSRL/OoT-Randomizer#295]
So during our last multi world we encountered a few bugs with the free scarecrow song option.
[The first one worked fine.](https://clips.twitch.tv/ProtectiveRamshacklePresidentTheTarFu)
[Afterwards he didn't really](https://clips.twitch.tv/TrustworthyBlazingRaccoonTinyFace) + [want to show up anymore.](https://clips.twitch.tv/BlightedSmallVanillaRaccAttack)
[And then this happened oO](https://clips.twitch.tv/DiligentCharmingCookieDatBoi)
Not really sure what's going on there :P

**Comment by phixtyseven** [comment]
I love that last clip. Pierre is clearly a bit buggy, but I'm glad this solution seems to be going over well (as far as I can tell).

**Comment by pkmnfrk** [comment]
If I may make a suggestion regarding the settings, (assuming the issue is trying to distinguish the notes from other meanings), why not tack the song to the end, using another character to delimit it? Eg, "BL8HBL4H:DAAAAAAA"

Regarding the bug itself, it seems that if he doesn't show up (which for me usually happens in the Sacred Forest Meadow and on top of Gerudo Fortress), just playing any 5 notes is enough to make him appear (and then the game gets confused and keeps the ocarina playing during normal game play)

**Comment by Hamsda** [comment]
I'm not sure what you mean by `distinguish the notes from other meanings`, but the issue is that the song itself kinda has to be part of the settings even though it really shouldn't be, because different players want different songs (so it's closer to a cosmetic even though it isn't).

From what I've experienced so far it has nothing to do with the location, but just the very first time it works as intended and afterwards he glitches out. Most of the time just sitting with the ocarina out will make him spawn then, no note playing required.

**Comment by pkmnfrk** [comment]
I was guessing about what the issue with the custom song is. Clearly, I was wrong :)

**Comment by phixtyseven** [comment]
The current solution shouldn't be super hard to fix afaik. Even if it somehow couldn't be done, it could be changed so that pierre pops up consistently without pulling out ocarina at all, this just isn't the preferred behavior.

**Comment by TestRunnerSRL** [comment]
Should be working ok now
