### ISSUE TITLE
Cannot beat game!

### ISSUE THREAD

**Issue by Cuphat** [TestRunnerSRL/OoT-Randomizer#311]
Happens especially often with 'No Ocarina of Time Reward' since your refactor on it, but I've also had it trigger without it rarely.

Settings String: BRUA4ACALCSCNAMCAB2JB, Seed: 4ZQPTHPMV7-1
Settings String: BRUA4ACALCSCECMCAB2JB, Seed: 5PBOX14WY3-27 for one without 'No Ocarina of Time Reward'

**Comment by r0bd0g** [comment]
I don't think that No Song from Ocarina of Time is a setting that can work, ever, in combination with all locations reachable and songs not being world shuffled. Songs are progression items. Progression items have to be reachable or else locations could become permanently unreachable. And attempting to turn off a song location will mean that there are not enough locations to place all of the songs. I don't know how you've attempted to get around this (necessary?) limitation, but here are some ideas on how it might work.

1. One idea might be to turn on beatable only (or something equivalent to that) for a brief moment while attempting to place the ocarina of time song. The problem is that this could potentially lock you out of locations forever. Nothing stops it from putting Zelda's Lullaby there at that time, and one of the stone dungeons could be Lullaby locked. Just like that, a lot of locations become completely unreachable. I don't think any implementation along these lines can work at all.

2. Another idea might be to change Serenade and Prelude into items that are not considered to be progression. Then, at least under that combination of settings, the Ocarina of Time song will always be one of the two of those songs. This actually works, but I don't think it's particularly desirable behaviour. I think it would play pretty poorly to always know that one of those two songs will be at that location, and to never be able to have both of those two songs at the same time in any seed.

3. Honestly I think I would prefer the enforce that the combination of song shuffle off, all locations reachable, and no song from ocarina of time just not be allowed to be used.

Can you explain to me what you've actually done to try and implement this?

**Comment by r0bd0g** [comment]
I think the issue with TR's implementation is probably that the leftover song is added to the prog item pool? And since the song isn't even placed in the SoT location yet, that can_play code doesn't activate either, so it thinks it can use that song to obtain things. Probably? He asserts in his comment that the game is beatable, but that test was removed. So there's no test that the game is actually beatable without the songs that failed to place anywhere.

The fact that it fails even without that option set is concerning. I'm not sure how it's able to tell between... unable to place the song due to that location being unusable, or unable to place a song due to other conflicts.

**Comment by Cuphat** [comment]
> I looked over cuphat's implementation and I suspect it works?
> 
> I don't totally understand why his modification to can_play was necessary (I think it's to prevent songs from locking themselves behind whatever song is at the sot location?), but looking at it though I wonder if something strange happens if a song from somebody else's world gets placed at your SoT location? I think it's possible for that to happen if songs are world-shuffled and it's beatable only. I'm not sure if it might cause it to think that that song isn't playable for you.
> 
> So I feel like that addition to can_play should be deactivated if songs are world-shuffled?

It's mainly so that nothing placed after songs is able to use the song there. You are correct, though, I did forget to check for `shuffle_songs` in there, so there's a rare but definitely there chance of it causing undesirable stuff in multi-world with song shuffle on.

**Comment by r0bd0g** [comment]
Song from Ocarina of Time is allowed to have unneeded progression items even when disabled, with all locations reachable on. This is different from all other disabling options, which, afaik, do not allow progression items of any kind with all reachable. Obviously this is necessary when songs are not shuffled, as all songs are progression items. However, the current implementation keeps that behaviour, even when songs are world-shuffled. I don't like this inconsistency and I don't think it should be the case that the song location is special in this way even when songs are world-shuffled.

I suspect you won't feel the need to change it, but I at least wanted to make sure you were aware of this.

**Comment by TestRunnerSRL** [comment]
I generally agree, however the way the the songs work is how I'd prefer it. I'll probably write something a bit more generalized to work for all locations this way.

**Comment by r0bd0g** [comment]
I think I'd prefer the opposite, where even in beatable only, no progression items can go there. But I'll take consistency over what it's like now I guess.

**Comment by r0bd0g** [comment]
I didn't look at the code again today but I was thinking there might be one last thing weird about disabled locations?

They're allowed to have progression items that lock other locations at the moment the progression item is placed, but then after that, the item there can never be obtained, so further progression items can never be placed behind it, though those locations might still technically be reachable. I can't really think of a fix. It might be possible to scan for unreachable locations from time to time and flag those as disabled, but I don't think that really fully solves it either.

**Comment by TestRunnerSRL** [comment]
I don't see this as a problem

**Comment by Cuphat** [comment]
I think this particular bug is fixed for now, so I'll close it.
