### ISSUE TITLE
The order of menu items is not consistent on python 3.5

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#416]
Do we still supposedly support 3.5?
This is the problem that TrenteR_TR was having, right?

**Comment by LostThePirate** [comment]
I was always told minimum 3.6, but to use 3.7 to be safe. Could be outdated/inaccurate info, though.

**Comment by flagrama** [comment]
This has come up before: https://github.com/AmazingAmpharos/OoT-Randomizer/issues/45#issuecomment-426673558

Python 3.5 doesn't sort Dicts. 3.5 is minimally supported for rando, but I don't think too much specific dev is going to be done to make it perfectly mimic 3.6+ as that would require us to change otherwise already perfectly working code.

**Comment by r0bd0g** [comment]
If python 3.5 is to be dropped maybe something should be done then to make it fail so that nobody falls for the trap.

**Comment by rlbond86** [comment]
This could be fixed by using `OrderedDict`s instead of `dict`s for all of the GUI items, but considering python `dict`s are sorted beginning in 3.6 I don't think it will be addressed.

**Comment by phixtyseven** [comment]
I think it should be done for correctness, but I think we might as well drop support for Python 3.5 for now, anyway.

**Comment by TestRunnerSRL** [comment]
Well we'll see when a million people complain
