### ISSUE TITLE
Alternative Idea For "100 Skultullas" Bridge Requirement

### ISSUE THREAD

**Issue by XerShade** [TestRunnerSRL/OoT-Randomizer#422]
I've found when doing this by the time you can actually get into Ganon's Castle that the items in there are pretty much junk or not required. I was wondering if it would be possible instead to make it so the 100 Skulltula house reward gives you the Boss Key for Ganon's Tower instead, and the castle and trials are open.

**Comment by flagrama** [comment]
100 Skulls as a bridge requirement is kind of more of a meme option for people who wanted to have 100 Skulltulas give an item, since people are always asking for 100 Skulls to be hacked to give something other than money. Most people don't want that check added as it would be incredibly time consuming so nobody wants to figure it out. Since you would already have all the items by the time you have 100 Skulls, and since there aren't any inside of Ganon's Castle anyway, it was decided that making it a bridge requirement instead was as close as the devs were to compromise on that suggestion.

If you or someone you know is able to and wants to add the 100 Skulls check to the randomizer though, go right ahead. You'll probably be able to use plandomizer to force an item in any location soon too so you'd effectively have what you want. Just know that most people are going to disable that location just as often as the disable Mask of Truth (and probably Ocarina of Time/Song of Time come 4.0) which is "always"

**Comment by TestRunnerSRL** [comment]
This would also be somewhat difficult to implement, for an option that no one would ever play with. So It's unlikely this will be implemented.

**Comment by OlafurKrH** [comment]
No joke, I would be interested in trying it out at least once... maybe more often if I actually enjoy it. If it's not gonna be implemented then that's fine with me, but just giving my take on this.

**Comment by EvilApple567** [comment]
As someone who always 100% their seeds (I just enjoy the surprise and variety of each playthrough), I would use this option everytime. My brother and friend also prefer to 100% their seeds as well, and since 100 GS is likely the last thing to be accomplished in a 100% run, it would add some really nice "legitimacy" to doing it all. Like the OP said, not closing off Ganon's Castle and the trials is important because of how much there is to do there with various items.

If it's too difficult to implement for its perceived worth, I understand, but there's definitely some genuine interest in this option and I hope it's reconsidered!

**Comment by XerShade** [comment]
Honestly the hardest thing would be finding the place to manipulate the ROM. If I knew ASM I would just do it myself, but there's no location defined for the 100 Skulltula reward in the python code.
