### ISSUE TITLE
Maybe N64-specific, maybe-boots related crashes?

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#441]
https://clips.twitch.tv/LongEnthusiasticHornetSoonerLater
https://clips.twitch.tv/RudeSincereMonitorCharlieBitMe

OoT Randomizer Version 3.12.1 f.LUM  -  Seed: FL41LOBSWH

File Select Hash:
    Map
    Mirror Shield
    Deku Stick
    Skull Token
    Bow

Settings (BRPC2DAJAAXEAWAAAGSFBHKLA):

**Comment by fig02** [comment]
The reason why I think its most likely boots related is because I had no issues until getting the Iron Boots as shown in the clip. And sgt had no issues until he got hoverboots as child and then went adult.

However MikeKatz was in this race and having crashing issues from the beginning. So Im not really sure what to make of that.

**Comment by mzxrules** [comment]
Posting to prevent stuff from being buried in Discord. 

Fig's crash debugger complains of an RCP hung up error, suggests that it is an issue with drawing the boots icon. The following is the display list being generated when both boots have been obtained.

> 17A5A8: DE000000 805CFBF0 // G_DL Jump and Link (jumps to the dlist set up by draw_setup in gfx.c)
17A5B0: E7000000 00000000 // G_RDPPIPESYNC
17A5B8: FC119623 FF2FFFFF // G_SETCOMBINE
17A5C0: FA000000 FFFFFFFF // G_SETPRIMCOLOR
17A5C8: FD70001F 804086C4 // G_SETTIMG G_IM_FMT_IA G_IM_SIZ_16b
17A5D0: F5701000 07000000 // G_SETTILE TILE 7 G_IM_FMT_IA G_IM_SIZ_16b line 8 PAL 0
17A5D8: E6000000 00000000 // G_RDPLOADSYNC
17A5E0: F4000000 0707C07C // G_LOADTILE TILE 7 ST (0.00,0.00), (31.00,31.00)
17A5E8: E7000000 00000000 // G_RDPPIPESYNC
17A5F0: F5701000 00000000 // G_SETTILE TILE 0 G_IM_FMT_IA G_IM_SIZ_16b line 8 PAL 0
17A5F8: F2000000 0007C07C // G_SETTILESIZE TILE 0 ST (0.00,0.00), (31.00,31.00)
17A600: E447C140 0043C100 // G_TEXRECT
17A608: E1000000 00000000 // G_RDPHALF_1
17A610: F1000000 08000800 // G_RDPHALF_2
17A618: FD18001F 805899C0 // G_SETTIMG G_IM_FMT_RGBA G_IM_SIZ_32b
17A620: F5181000 07000000 // G_SETTILE TILE 7 G_IM_FMT_RGBA G_IM_SIZ_32b line 8 PAL 0
17A628: E6000000 00000000 // G_RDPLOADSYNC
17A630: F4000000 0707C07C // G_LOADTILE TILE 7 ST (0.00,0.00), (31.00,31.00)
17A638: E7000000 00000000 // G_RDPPIPESYNC
17A640: F5181000 00000000 // G_SETTILE TILE 0 G_IM_FMT_RGBA G_IM_SIZ_32b line 8 PAL 0
17A648: F2000000 0007C07C // G_SETTILESIZE TILE 0 ST (0.00,0.00), (31.00,31.00)
17A650: E4440138 00410108 // G_TEXRECT
17A658: E1000000 00000000 // G_RDPHALF_1
17A660: F1000000 0AAA0AAA // G_RDPHALF_2
17A668: FD18001F 8058A9C0 // G_SETTIMG G_IM_FMT_RGBA G_IM_SIZ_32b
17A670: F5181000 07000000 // G_SETTILE TILE 7 G_IM_FMT_RGBA G_IM_SIZ_32b line 8 PAL 0
17A678: E6000000 00000000 // G_RDPLOADSYNC
17A680: F4000000 0707C07C // G_LOADTILE TILE 7 ST (0.00,0.00), (31.00,31.00)
17A688: E7000000 00000000 // G_RDPPIPESYNC
17A690: F5181000 00000000 // G_SETTILE TILE 0 G_IM_FMT_RGBA G_IM_SIZ_32b line 8 PAL 0
17A698: F2000000 0007C07C // G_SETTILESIZE TILE 0 ST (0.00,0.00), (31.00,31.00)
17A6A0: E44A4138 00474108 // G_TEXRECT
17A6A8: E1000000 00000000 // G_RDPHALF_1
17A6B0: F1000000 0AAA0AAA // G_RDPHALF_2


The theory is that the G_SETTIMG line is the culprit for the crash, since forcing the dpad texture to be 8 byte aligned seems to have fixed the issue. What's weird is that the issue hasn't manifested itself before this, since the texture has been misaligned before. It's possible that it's a bug in the microcode itself specific to IA textures.

**Comment by krimtonz** [comment]
This should be fixed in https://github.com/TestRunnerSRL/OoT-Randomizer/pull/449

**Comment by sorokya** [comment]
I had this same issue when I got Hover boots in ice cavern. Tried twice and got a crash both times.
![crash1](https://i.imgur.com/OnSCWCX.jpg)
![crash2](https://i.imgur.com/wqTTWaP.jpg)
![crash3](https://i.imgur.com/b9jEY0m.jpg)

**Comment by krimtonz** [comment]
Thanks for the debugging information.  This has been fixed pending a merge by tr. in the meantime you can use my dev branch or mzxs texture branch.

**Comment by sorokya** [comment]
Thanks, I regenerated my rom on r0bd0g/Texture and the bug is fixed

**Comment by DatXFire** [comment]
Fixed as part of #449 rebase.
