### ISSUE TITLE
Elevator in Jabu started at the bottom when entering from upper door

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#450]
3.11.24
I thought this was fixed?

**Comment by mzxrules** [comment]
this was discussed in the discord, but there are two possible reasons this is happening, both of which appear in this small segment and should be easy to fix:

> 	mtc1	t0, f3 ; f3 = -1200
	c.lt.s	f2, f3
	bc1t	@@bottom

The first issue is the use of the f3 register; On n64, only even numbered floating point registers are used. I am unsure of how the N64 behaves with odd numbered floating point registers.

The second issue is that mtc1 and c.cond.fmt ops require a delay between, otherwise their results are undefined. 

I believe Fig has written a proper fix for this

**Comment by fig02** [comment]
Yup, fix is done and tested to be ok on N64. Though it will need more testing as the results were inconsistent before (as in, it would still work sometimes even on console). One test is not enough but we'll need to wait till people complete some seeds on it

https://github.com/TestRunnerSRL/OoT-Randomizer/pull/454

**Comment by DatXFire** [comment]
Should be fixed as part of #454 rebase.
