### ISSUE TITLE
Spirit temple listed as barren with woth item on silver gauntlets chest

### ISSUE THREAD

**Issue by DatXFire** [TestRunnerSRL/OoT-Randomizer#459]
**Describe the bug**
Progressive Hookshot found in Silver Gauntlets chest which is required for Light Medallion on Morpha, but there is a hint for Spirit Temple as a barren location.

**To Reproduce**
Setting: BMPCJMA2FAYESNJSJTSTAUAWSWSYAAAAEBRJLA
Seed: ZPOCLELE89

**Expected behavior**
Spirit Temple outer chests should be considered part of Spirit Temple, and not barren if they contain a woth item.

**Randomizer Version Numer**
3.12.3

**Platform**
Randomizer

[OoT_30F6F_ZPOCLELE89_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2725841/OoT_30F6F_ZPOCLELE89_Spoiler.txt)

**Comment by r0bd0g** [comment]
Those chests are part of Desert Colossus.

**Comment by rlbond86** [comment]
Those chests are clearly part of the Spirit Temple. Or do you think that the non-random Spirit Temple doesn't have dungeon items?

**Comment by rlbond86** [comment]
Also it's a useless hint if you put those treasures as part of the Desert Colossus. The point of the hint is to tell you that you don't need to go to the Spirit Temple. Right now if you get that hint you STILL need to go through it.

**Comment by rlbond86** [comment]
But not for picking up items. For example, if a required dungeon has the light medallion and is barren, you can finish it at any time because it doesn't have any progression items. Unless it's the Spirit Temple apparently.

**Comment by r0bd0g** [comment]
Even stone dungeons. Could be a surprise AD you didn't see coming.

**Comment by rlbond86** [comment]
AD?

**Comment by rlbond86** [comment]
On the other hand, small keys and the Boss key for the Spirit Temple never show up in those chests...

**Comment by DatXFire** [comment]
AD = All Dungeons

Anyways we discussed this a bit more the other day in the public dev channel on discord, and kind of stuck about what to do here. It was considered to ask the runners their thoughts on the matter as well. The only thing we all really agreed on is that whatever gets chosen, it should be consistent for the purposes of item placement, woth, and barren hints.

**Comment by TestRunnerSRL** [comment]
This was something on debate back in 3.0 among the devs. Currently the hands are not part of the dungeon in all context except 1 item per dungeon. Personally it should part of the dungeon, but AA (and other devs) did not like the idea of getting a key for Spirit when there was no key count displayed when it wasn't keysanity, etc. From my perspective, it's really hard to not consider them part of the dungeon because of how they are designed, although entrance shuffle would kinda change this entirely.

So in general, I agree that it's pretty inconsistent, and whether the hands are considered part of the dungeon or not is a pretty old debate, many years before rando was every conceived. I would rather them just be part of the dungeon, but this is something that can really go either way. I'm not going to change this for 4.0 tho, since it's too close.

**Comment by DatXFire** [comment]
I think that's fair, it would be a big change to how the dungeon works this close to 4.0 and the tournament. Something to consider for future releases at the least, and maybe start getting a feel for what runners think as well.

**Comment by DatXFire** [comment]
Changed with 4befc7c
