### ISSUE TITLE
Sun Song in Non-Day change scenarios.

### ISSUE THREAD

**Issue by AvosMeLardo** [TestRunnerSRL/OoT-Randomizer#472]
**Describe the bug**
I experienced a glitch with the Sun Song inside of dungeon like areas that would stun Redeads / Gibdos or the Graveyard Sun Song Chest. The game would freeze after the song leaving Link standing there with the Ocarina to his mouth, never loading the Freezing Gibdo's / Sun Song Chest. It is the same for both Young and Adult Link. I've been playing on RetroArch Core Nintendo / Nintendo 64 (ParaLLEl N64) in Exclusive Full Screen mode has given me the best results to play the randomizer. I have done well over 20-30 runs of the game as new patches come out I start over almost every time. The current version of the OoT Randomizer is 3.12.3 f.LUM. I usually do not get the Sun Song til late but this last play thru I got it early and of all other times I have used it, it has worked just fine until this last build. Possible causes could have been that the Random Song notes made the Sun Song 8 notes long, or that the song is trying to make the day change where it normally souldn't.

**To Reproduce**
The setting string I used was BAWQ8DS67XMDAAJMW6EPGAE5NAVA : and the seed was M5VMBVJ9UZ

**Expected behavior**
Normally on previous runs the Sun Song would go through and Link would put away his Ocarina and play would resume and either Redeads / Gibdos would freeze or the Sun Song Chest would appear.

**Screenshots**
N/A

**Randomizer Version Numer**
3.12.3 f.LUM

**Platform**
RetroArch Core Nintendo / Nintendo 64 (ParaLLEl N64) in Exclusive Full Screen mode for Windows 10 x64

**Additional context**

**Comment by flagrama** [comment]
"Randomize Ocarina Notes" I have seen this behaviour once before with this setting.

@AvosMeLardo Could you try playing Sun's Song in Hyrule Field too? For some reason Sun's Song will sometimes freeze you in place until the day/night transition finishes (wolf howls or cucco crows) with Randomize Ocarina Notes on it seems. Since a dungeon doesn't have a day/night transition you get permanently stuck in the Ocarina playing stance instead.

I've reproduced it the last time this happened on N64 hardware with ED64 so it's not just some emulator bug.

**Comment by AvosMeLardo** [comment]
I did play it in the Hyrule Field for both the change to night>day and day>night. It did seem to feel longer to have the day move before play returned to control. It must be a core game mechanic cause while Adult Link stands there I can still toggle the Quick Boot change Dpad icon on and off which is randomizer exclusive.

Thanks for the confirmation that it is to do with the "Randomize Ocarina Notes" setting.

**Comment by r0bd0g** [comment]
Was this bug ever addressed? Why was the issue closed?

**Comment by flagrama** [comment]
Don't think anybody has been able to reproduce it or has run into it since 5.0 released. May have been a side effect of the old Malon Sun's Song softlock fix, that is now fixed properly.

**Comment by flagrama** [comment]
Looks like Suns Song was in a shop in this seed? Maybe someone should make sure buying it from a shop, specifically `Zora Shop Item 5:                                      Suns Song [Costs 70 Rupees]` doesn't create the issue.

**Comment by r0bd0g** [comment]
It sounded like the bug was that a really long sun's song was causing the game to softlock. When did ocarina notes stop being a cosmetic option? If it was cosmetic at the time, that might be why nobody could reproduce. And I guess sometimes these kinds of things can depend on lag? So it could vary depending on what platform they were using.

**Comment by flagrama** [comment]
Ocarina Notes was never cosmetic. I was able to reproduce all issues on hardware and emulator. While the chances of a long song, or maybe a song that ends with a rest, are not impossible, I tried over 400 seeds in 5.2 trying to create a seed that produced such a Sun's Song even modifying the code that generates the song. I was not able to reproduce it.

**Comment by r0bd0g** [comment]
Oh, right, I was thinking of the interaction with scarecrow and ocarina notes making scarecrow not cosmetic anymore.
Weird though that nobody seems to have intentionally fixed this, but it seems gone...
