### ISSUE TITLE
Carpet Salesman 1st Logical Explosives with Chu Logic Off

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#688]
https://cdn.discordapp.com/attachments/438698093354156032/576082375575076891/OoT_85984_VCZFFFERJO_Spoiler.json

Zannick?
There are no checks anymore for the carpet guy and chus in logic, so you probably have to... add that to the world logic?

**Comment by r0bd0g** [comment]
TBH this behaviour could be a trick option lol...

**Comment by r0bd0g** [comment]
Has anybody thought about bombchu sources when chus in logic is off, in ER? I think it's only bombchu bowling??? But I don't see why carpet guy couldn't be your first source of chus in ER after finding a bomb bag...

**Comment by Zannick** [comment]
This is a very impressive seed with all Bomb Bags behind bombchus/explosives checks...

Ok, I see what happened with that change. In simplifying the bombchu logic to make it clearer what has_bombchus (renewable bombchus), has_bombchus_item (unlocked bombchus), and can_buy_bombchus (collected renewable bombchus, yes, the same as has_bombchus) do, we removed a Has('Bomb Bag') check for has_bombchus since it was redundant with has_bombchus_item (the requirements to buy chus and play bowling) and has_explosives (has_bombs or has_bombchus). I had interpreted the logic as saying chus were okay as a first explosives because I misunderstood that.

But I'm not sure I understand your latter comment about keeping carpet guy bombchus or not. What exactly should be the decision here? If chus in logic is off, and carpet guy is NOT a good first source of explosives, then has_explosives should not include chus, since in all cases has_bombchus must be false without a Bomb Bag. If chus in logic is on, is carpet guy still a good first source of explosives?

```python
def has_explosives(self):
    return self.has_bombs or (self.world.bombchus_in_logic and self.has_bombchus)
```

Or are you saying he should only count as unlocking bombchus in chus-in-logic, by dropping Bombchus instead of Bombchu Drop? (This would make him irrelevant in chus-not-in-logic seeds.)

(I would rather not make him function differently in ER vs non-ER; even in non-ER chus-in-logic he could be your only source of bombchus--is he not annoying enough to buy from then?)

**Comment by Zannick** [comment]
One other thing I meant to test in my last ER seed: does buying from the Salesman enable bombchu bowling with chus-not-in-logic? If not, then he should not grant has_bombchus_item because that is the Bombchu Bowling check, and therefore he must always be entirely irrelevant in chus-not-in-logic (since Bowling gives renewable bombchus not from a shop). And my suggested change to has_explosives above does not fix that (the seed has two bomb bags in bombchu bowling).

**Comment by r0bd0g** [comment]
So the way it probably has to be is...
- if chus are not in logic, the carpet guy is a logical source of bombchus only if you have bomb bag already.
- if chus are in logic, the carpet guy is a source of only bombchu item, not of bombchu refills.

**Comment by Zannick** [comment]
I made it so he's only a source of bombchus item, not refills. For chus not in logic, that's an overcorrection since it makes him not a logical source at all. I'll make it so logic can't use chus without bomb bag in chus-not-in-logic. That will let us later make him a source of bombchus for not-in-logic.
