### ISSUE TITLE
Sounds like... start with max rupees is giving the wrong amount when you find a wallet or something?

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#708]
Cubsrule21Today at 11:33 PM
interesting one from the #gameplay-support channel

So probably most definitely a bug, may or may not be known, on 4.12.1. Doing a multiworld, and had start with max rupees, but not start with the tycoon wallet.  I got my own wallet, which was the first one, and then I immediately got 500 rupees, and my counter isn't green, so I'm guessing I've got the tycoon wallet.

Wait, I just got a purple rupee and my count went back down to 200 and it's green. So I guess it's just a graphical thing.

@Dom

reporter is gonna ping me when someone else finds a wallet, to see if the issue happens again

OoT_D68B6_DBJC2HMWXF_W4_Spoiler.json
335.03 KB

there's the spoiler, if it helps at all

**Comment by dombarrieau** [comment]
Pretty sure what is happening is the code to give the rupees gets run when you pick up a wallet, regardless of who's it is in Multiworld

**Comment by r0bd0g** [comment]
That sounds like a pretty good theory. Maybe they'd picked up someone else's wallet earlier?

**Comment by TestRunnerSRL** [comment]
Yeah that sounds like the problem. If you get a wallet for someone else, then the code thinks it's for you and give your (current wallet level + 1) rupees, which isn't correct

**Comment by dombarrieau** [comment]
So someone else ran into this running a solo seed, so it doesn't seem to be related to MW. I doubt it, but am wondering if its related to save->wallet having a higher value than it "should", or the array we read from the game (#define rupee_cap ((uint16_t*)0x800F8CEC)) being "incorrect". The error is intermittent and I'm not able to reproduce it, although I haven't run through the seed marked above, because I don't want to run through a 4 person MW seed solo to try to reproduce it.

**Comment by Nicholas-Steel** [comment]
Another report on the issue: https://discordapp.com/channels/274180765816848384/274186223147417600/586100397836468234

**Comment by dombarrieau** [comment]
Roman isolated the issue, should be PR-ed in the next few days
