### ISSUE TITLE
Floating Point Exception crash on N64 during the credits

### ISSUE THREAD

**Issue by mzxrules** [TestRunnerSRL/OoT-Randomizer#745]
Dev Version 4.11.7

https://imgur.com/a/UcpgBih

the final fault is in the draw english text function. it's computing the width? of the null character, but the character table starts at ascii 32 (space)

**Comment by r0bd0g** [comment]
For the record I guess, the credits seem to crash on VC as well. It doesn't always happen though? So it's one of those annoying inconsistent thing that doesn't always happen.

**Comment by fig02** [comment]
It was discussed in discord but I should mention here:
The crash is due to an overflow with our text table. The defined size is 0x43A8 but the limit should be 0x4220 to avoid writing into the staff roll table. 
The crash currently only occurs when using shop sanity 4, because the last few text entries overflow into the staff roll. To fix this we will need to find a place to continue an extension of this table.

**Comment by flagrama** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Text Table Overflow (Credits Crash)](https://trello.com/c/vNjxgdOh/5-text-table-overflow-credits-crash)
