### ISSUE TITLE
Equipped Magical Arrows replaced with Bow on time travel

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#834]
It happens on 4.0 and I doubt anybody's changed anything here recently.

**Comment by dotzo** [comment]
On dev, it becomes whatever is in the bow slot. It seems to be reading the highlighted selection rather than the c-button item upon time travel. To note, if you have a quiver and no bow nothing else happens, and it changing to bow doesn't give you a quiver. This is solely an item menu issue, not a full pause menu issue. Just an inconvenience, nothing game breaking.

**Comment by r0bd0g** [comment]
TBH I can't remember this happening in vanilla but I can't say I've ever tried it. I think it only happens in vanilla though, if the inventory location has a bottle or a trade item?
