### ISSUE TITLE
[Suggestion] Improve Farores Wind

### ISSUE THREAD

**Issue by Hamsda** [TestRunnerSRL/OoT-Randomizer#84]
I think the vanilla behavior of Farores Wind warp point being dispelled when you go back and forth in time makes sense as child and adult are usually not supposed to be in the other ages dungeon.
During vanilla gameplay you are not really required to go deep into temples, leave them, switch ages, and come back, something that the randomizer logic might very well require you to do even multiple times.
To make Farores Wind a bit more useful, it would be wonderful if we could get one of the following improvements:

1. FW warp does not get dispelled when switching ages
2. Two separate FW warps, one for child and one for adult, which don't get dispelled either

The first suggestion might lead to some unwanted behavior, especially for the more casual players, with Link ending up in a dungeon not made for his age. It would still be an overall improvement imo.
The second idea is the one I really like though. It immensely improves the usability of FW, especially in a rando setting, and doesn't interfere with casual gameplay.
I am not sure how easily doable either one would be as I'm not versed with ASM.

**Comment by TestRunnerSRL** [comment]
The first option breaks a lot of logic since there's a lot of places (not just dungeons) that are only accessible at various ages with specific items. The second seems ok, but I have no idea how to go about implementing it

**Comment by Hamsda** [comment]
Maybe @mzxrules or @glankk could help with allowing two different FW spots?

**Comment by mzxrules** [comment]
Implementing something like that doesn't seem particularly too difficult. The important variables for the FW restore point are fully documented: You have one set of variables for the saved FW point, and a set of zoneout respawn variables which iirc is set on scene transition whenever the FW flag is set (been a while since I've messed with this). In theory it'd just be a matter of having an extra copy of both around and swapping it out whenever you travel through time. 

The primary issue is reserving space on the save file... you need no more than 0x28 bytes for the saved variables, though this can easily be reduced by quite a bit due to the saved variables being all s32 types.

**Comment by TestRunnerSRL** [comment]
You can probably do something like I did for the deku salescrub and use the unused variable in the permanant scene flags, or using non-dungeon scenes for their room/floor data. Just make sure you don't conflict with the deku scrub stuff I have in there I guess

**Comment by Hamsda** [comment]
I'm happy to hear you guys think this would be doable. :)
In yesterdays accessible weekly race separate child and adult FW points would have probably saved around 15 minutes or so, because of multiple dungeon dips and age switches to get something required.
