### ISSUE TITLE
[Feature Request] Add Majoras Mask Maps to entrance randomizer

### ISSUE THREAD

**Issue by sh4ni** [TestRunnerSRL/OoT-Randomizer#844]
I hope this is not something that is too far fetched, I saw Romhacks having MM Maps in Oot and vise versa.

If it's a space or allocation problem, some OoT maps could be replaced randomly bei MM Maps.

**Comment by aofengen** [comment]
never gonna happen. Copyright issues.

**Comment by LostThePirate** [comment]
This project will not be using assets from any outside IP.

**Comment by sh4ni** [comment]
You could request a MM Rom to extract the maps from. But it would make the process more complicated.

**Comment by aofengen** [comment]
that puts too much on the user to be worth it. Asking someone to obtain and provide one rom is bad enough - but two? no thanks. Plus, the logic hell and back-end work that would have to go into creating something like that far outweigh any potential benefit imo

**Comment by LostThePirate** [comment]
That wasn't my subjective opinion of this idea; it's the stance of the community to NOT jeopardize the game by infringing on outside IPs.

**Comment by TestRunnerSRL** [comment]
I was really confused when you said maps, but I guess pc fps modding terminology. And no we're not doing a mm cross over for reasons stated. Largely a combination of the fact that there is no logic for MM that and also because it would also require making many modifications to the game code to support a lot of MM's features. Let's put aside the fact that pretty much every dungeon is unbeatable without transformation masks
