### ISSUE TITLE
Tunics being made unable to be purchased in Shopsanity 

### ISSUE THREAD

**Issue by Luigimeansme** [TestRunnerSRL/OoT-Randomizer#90]
So I'm doing a run of Shopsanity right now, and I discovered that the Goron Tunic that you usually find in the Goron Shop was randomized to be in the Castle Town Potion Shop, making it unable to be purchased since Young Link cannot buy tunics, and the potion shop is moved to Kakariko as an adult, with different inventory. It isn't too big a deal, but something I thought was worth mentioning

**Comment by r0bd0g** [comment]
The logic knows you can't buy that tunic.

**Comment by TestRunnerSRL** [comment]
Yeah the shop is still reachable. The Goron Tunic is still available somewhere in the world in a chest. I wasn't completely sure if "All Locations Reachable" Should ensure you can buy the tunic or just that the physical shop location was reachable. Since there's already another tunic in the world, I figured this was fine as there's still always a tunic available.
