### ISSUE TITLE
Savestates Crashing in Bizhawk in 5.1

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#907]
We've got multiple reports of this, now. I don't know if there's something we did to cause this or what.

**Comment by JJ0033LL** [comment]
I used version 5.0.41 to create seed, Savestave crashes on this version. I tested few older vesions that i have in my computer (4.15.6 and 4.13.13) and they seem stable. I am using bizhawk 2.3.0. Haven't tested 5.1 yet. Added spoilerlog if that helps anything. Didn't create cosmetics log.


[OoT_83BB8_MUSTAMIES_W2_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/3639443/OoT_83BB8_MUSTAMIES_W2_Spoiler.txt)

**Comment by darkangel93x** [comment]
can be closed culprit was found

**Comment by r0bd0g** [comment]
Which was?

**Comment by flagrama** [comment]
For posterity since everyone is just keeping this secret answer to Discord:

Bizhawk doesn't enable the Expansion Pak by default. OoTR shouldn't even run without it, but somehow has carried on until recent changes. [Enabling the Expansion Pak](https://wiki.ootrandomizer.com/index.php?title=Bizhawk#Emulator_Setup) in the options solves the issue.

**Comment by Nicholas-Steel** [comment]
Is there a way to change the default setting so that a version of Bizhawk can be distributed with the new default?
