### ISSUE TITLE
Plando'd Expected Tricks are Ignored

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#932]
The settings page reports that the plando's tricks have been used, but in truth, the settings that were set in the GUI have been used instead. I would guess excluded locations probably is bugged the same way but I haven't confirmed it.

If you check the spoiler for this seed you can see it: https://ootrandomizer.com/seed/get?id=287961
Both Ocarinas are Ocarina locked (the logical one is in Ganon's, locked by Forest Temple access), and it waits until Goron Tunic to enter Fire Temple, as examples. The trick list shows backflip over mido off and fewer tunic requirements on, but if you import the settings string you can see that only backflip over mido is truly enabled.

**Comment by Zannick** [comment]
The settings string at the top of the page and the raw spoiler settings string differ, and everything else on the page matches the latter. I can't see the plando file so I'm not really sure which was which, but I definitely do see that the raw spoiler does not have Mido backflip on, yet is accessing the Sacred Meadow without Ocarina. I'll look into this.

**Comment by r0bd0g** [comment]
Alright I'm gonna make a random guess what the problem is, not having looked at the code at all, b/c that's fun to do, right? I'm guessing that these particular settings are the only ones bugged b/c they are lists, and when these list settings are getting copied over, they're just replacing a reference, and the original list is still somehow being used for actually genning the seed.

**Comment by Zannick** [comment]
Likely what's happening is the plando is overriding the settings without any effect, except to change what's written in the settings block in the spoiler. The tricks enabled are set as flags in the World object upon creation, and used when we generate the graph. So either:
* plando turns on all the tricks from the plando file without disabling any already set.
* plando applies the new trick list after the overworld graph is generated.

The question is, what's the right resolution here?
* Top-level tricks/excluded locations should take precedence over the plando (or plando only uses specific sections). This is tricky in general because plando could set all dungeons to vanilla but the settings could ask for n>0 MQ. This might be the actual behavior, in which case all we need to do is not change the spoiler output.
* Plando should take precedence (this means changing settings for a plando requires editing the plando file, and confusingly, the GUI will have no effect).
* The lists should be merged together. Excluded locations by union and tricks by intersection, because logic-wise it's better to err on the side of excluding locations and not considering tricks.

**Comment by r0bd0g** [comment]
In the example provided, it waits until Goron Tunic to collect any keys from Fire Temple, so the entire trick list provided by the plando is completely ignored.

The expected behaviour I would think would be that if a trick list is provided (even if it's blank), the plando's trick list completely replaces what was originally there.

**Comment by Hamsda** [comment]
Yeah I agree with r0bd0g, since that would match the behavior for other settings with the addition of being able to provide an empty list, but how else would you say "no tricks enabled".

**Comment by Zannick** [comment]
Are there cases in which one would make a plando without providing any tricks enabled, and someone else uses that plando and wants to enable tricks? If we just always use the plando trick list and settings, is there any reason why we don't disable all the settings plando sets when "enable plando" is on?

**Comment by flagrama** [comment]
Plando parsing happens well after hitting generate. I'm not sure how it affects the web side to try to parse it on open or anything either.

**Comment by Zannick** [comment]
I mean, Plando itself, not a specific plando. The plando editor has most settings there, we would just disable all of them in the randomizer settings UI to make it clear that plando's settings, whatever they are, take precedence.

**Comment by flagrama** [comment]
In that case you'll want to make sure that it is [actually consistent about that](https://discordapp.com/channels/274180765816848384/476723801032491008/649523720100249602).

**Comment by r0bd0g** [comment]
It seems this bug does not apply to excluded locations.

**Comment by Zannick** [comment]
I figured it out. We cache the initial list of tricks before loading the distribution file rather than after, so we exclusively use those tricks. When I reverse that, we'll exclusively use the distribution file's tricks, if any are given. (And if I understand this code right, there's a difference between `allowed_tricks` being set empty versus not listed at all. The Plando tool currently sets it to empty.)
