### ISSUE TITLE
Multiplayer Seeds Fail with certain settings...

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#98]
https://cdn.discordapp.com/attachments/438698093354156032/488318322480513054/Sans_titre_3.png

https://cdn.discordapp.com/attachments/438698093354156032/488318119484325898/Sans_titre_4.png

It has to be a multiplayer seed to fail.
I tried once with shopsanity off and it did not fail.

**Comment by TestRunnerSRL** [comment]
yeah it just means i'm writing too much text out, since a lot of is added for both shopsanity and coop. I'll either need to cut something back or look into expanding the table

**Comment by TestRunnerSRL** [comment]
Fixed in 607393b661b4e80ae199deb749c3888d87cfa066
This is kind of a patch, since this will continue to be a problem as more stuff is added. There's a huge amount of unused text from cutscenes that can be removed. I'd like to expand the table, but it's not an OVL file, so I don't know if that would be possible realistically.
